#ifndef CHTTPMODULE_GLOBAL_H
#define CHTTPMODULE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CHTTPMODULE_LIBRARY)
#  define CHTTPMODULESHARED_EXPORT Q_DECL_EXPORT
#else
#  define CHTTPMODULESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CHTTPMODULE_GLOBAL_H
